id: register-host-in-ansible-inventory
namespace: company.team

tasks:
  - id: set_vars
    type: io.kestra.plugin.core.execution.SetVariables
    variables:
      git_url: "https://github.com/jcbollingnet-homelab.git"
      target_branch: "main"
      commit_author_name: "Kestra Bot"
      commit_author_email: "kestra-bot@bollingnet.local"

      host: "{{ trigger.body.hostname }}"
      feature_branch: "inv/add-{{ trigger.body.hostname | replace({'.':'-'}) | lower }}-{{ execution.id | slice(0, 8) }}"
      repo_dir: "repo-{{ execution.id | slice(0, 8) }}"
      bootstrap_dir: "repo-bootstrap"

      inv_ns_path: "ansible/inventory.yml"

  - id: work
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: fetch_from_namespace
        type: io.kestra.plugin.core.namespace.DownloadFiles
        namespace: "{{ flow.namespace }}"
        files:
          - "ansible/**"
        allowFailure: true

      - id: git_clone_bootstrap
        type: io.kestra.plugin.git.Clone
        url: "{{ vars.git_url }}"
        branch: "{{ vars.target_branch }}"
        directory: "{{ vars.bootstrap_dir }}"
        username: "{{ secret('GIT_USERNAME') }}"
        password: "{{ secret('GIT_TOKEN') }}"

      - id: bootstrap_inventory_if_missing
        type: io.kestra.plugin.scripts.shell.Commands
        commands:
          - |
            set -eu
            if [ -f "{{ vars.inv_ns_path }}" ]; then
              echo "Inventory present from Namespace Files: {{ vars.inv_ns_path }}"
            else
              echo "Inventory missing; bootstrapping from repo if possible."
              mkdir -p "$(dirname "{{ vars.inv_ns_path }}")"
              if [ -f "{{ vars.bootstrap_dir }}/ansible/inventory.yaml" ]; then
                cp -v "{{ vars.bootstrap_dir }}/ansible/inventory.yaml" "{{ vars.inv_ns_path }}"
                echo "Bootstrapped from repo inventory.yaml -> {{ vars.inv_ns_path }}"
              elif [ -f "{{ vars.bootstrap_dir }}/ansible/inventory.yml" ]; then
                cp -v "{{ vars.bootstrap_dir }}/ansible/inventory.yml" "{{ vars.inv_ns_path }}"
                echo "Bootstrapped from repo inventory.yml -> {{ vars.inv_ns_path }}"
              else
                printf "all:\n  hosts:\n" > "{{ vars.inv_ns_path }}"
                echo "Created minimal skeleton at {{ vars.inv_ns_path }}"
              fi
            fi
            echo "== BEFORE upsert =="
            sed -n '1,200p' "{{ vars.inv_ns_path }}" || true

      - id: upsert_yaml
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          image: python:3.11-alpine
        commands:
          - |
            set -euo pipefail
            python -m pip install --no-cache-dir --upgrade pip ruamel.yaml
            python - <<'PY'
            import pathlib, sys
            from ruamel.yaml import YAML
            from ruamel.yaml.comments import CommentedMap

            inv_path = pathlib.Path("{{ vars.inv_ns_path }}")
            host = "{{ vars.host }}"

            if not inv_path.exists() or inv_path.stat().st_size == 0:
                print(f"[FATAL] Inventory not loaded before upsert: {inv_path}", file=sys.stderr)
                sys.exit(10)

            yaml = YAML()
            yaml.indent(mapping=2, sequence=4, offset=2)

            with inv_path.open("r") as f:
                data = yaml.load(f)

            if not isinstance(data, dict):
                print("[FATAL] Inventory is not a mapping; refusing to overwrite", file=sys.stderr)
                sys.exit(11)

            data.setdefault("all", CommentedMap())
            data["all"].setdefault("hosts", CommentedMap())
            hosts = data["all"]["hosts"]

            if host not in hosts:
                hosts[host] = None  # emits "host:" (no "{}")

            with inv_path.open("w") as f:
                yaml.dump(data, f)
            PY

            echo "== AFTER upsert =="
            sed -n '1,200p' "{{ vars.inv_ns_path }}" || true

      - id: upload_to_namespace
        type: io.kestra.plugin.core.namespace.UploadFiles
        namespace: "{{ flow.namespace }}"
        files:
          - to: "{{ vars.inv_ns_path }}"
            from: "{{ vars.inv_ns_path }}"

      - id: ansible_inventory_check
        type: io.kestra.plugin.ansible.cli.AnsibleCLI
        containerImage: cytopia/ansible:latest-tools
        namespaceFiles:
          enabled: true
          include:
            - "ansible/**"
        outputFiles:
          - ansible-inventory.json
        commands:
          - |
            set -euo pipefail
            test -f "{{ vars.inv_ns_path }}" || { echo "Inventory not mounted: {{ vars.inv_ns_path }}"; ls -la ansible || true; exit 1; }
            echo "== mounted namespace files =="
            ls -la ansible || true
            echo "--- {{ vars.inv_ns_path }} ---"
            sed -n '1,200p' "{{ vars.inv_ns_path }}" || true
            ansible-inventory -i "{{ vars.inv_ns_path }}" --list | tee ansible-inventory.json

      - id: ensure_empty_repo_dir
        type: io.kestra.plugin.scripts.shell.Commands
        commands:
          - |
            set -eu
            rm -rf "{{ vars.repo_dir }}"
            mkdir -p "{{ vars.repo_dir }}"

      - id: git_clone
        type: io.kestra.plugin.git.Clone
        url: "{{ vars.git_url }}"
        branch: "{{ vars.target_branch }}"
        directory: "{{ vars.repo_dir }}"
        username: "{{ secret('GIT_USERNAME') }}"
        password: "{{ secret('GIT_TOKEN') }}"

      - id: copy_into_repo_with_rename
        type: io.kestra.plugin.scripts.shell.Commands
        commands:
          - |
            set -eu
            echo "== copying {{ vars.inv_ns_path }} into repo checkout as inventory.yaml =="
            test -f "{{ vars.inv_ns_path }}" || { echo "missing {{ vars.inv_ns_path }}"; exit 1; }
            mkdir -p "{{ vars.repo_dir }}/ansible"
            cp -v "{{ vars.inv_ns_path }}" "{{ vars.repo_dir }}/ansible/inventory.yaml"
            git -C "{{ vars.repo_dir }}" add "ansible/inventory.yaml"
            echo "== repo tree after copy =="
            find "{{ vars.repo_dir }}" -maxdepth 3 -type f | sort

      - id: git_push
        type: io.kestra.plugin.git.Push
        directory: "{{ vars.repo_dir }}"
        branch: "{{ vars.feature_branch }}"
        username: "{{ secret('GIT_USERNAME') }}"
        password: "{{ secret('GIT_TOKEN') }}"
        commitMessage: "inventory: add {{ vars.host }}"
        author:
          name: "{{ vars.commit_author_name }}"
          email: "{{ vars.commit_author_email }}"

  - id: open_pr
    type: io.kestra.plugin.github.pulls.Create
    oauthToken: "{{ secret('GIT_TOKEN') }}"
    repository: "jcbolling/bollingnet-homelab"
    sourceBranch: "{{ vars.feature_branch }}"
    targetBranch: "{{ vars.target_branch }}"
    title: "Add {{ vars.host }} to inventory"
    body: |
      This PR was created by Kestra.

      **Host:** `{{ vars.host }}`

      ### `ansible-inventory --list` (JSON)
      ```json
      {{ read(outputs.ansible_inventory_check.outputFiles["ansible-inventory.json"]) }}
      ```

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"
