id: register-host-in-ansible-inventory
namespace: company.team

variables:
  ns_inventory_path: ansible/inventory.yaml
  git_url: https://github.com/jcbolling/bollingnet-homelab.git
  target_branch: main
  commit_author_name: "Kestra Bot"
  commit_author_email: "kestra-bot@bollingnet.local"

tasks:
  - id: set_vars
    type: io.kestra.plugin.core.execution.SetVariables
    variables:
      host: "{{ trigger.body.hostname }}"
      feature_branch: "inv/add-{{ trigger.body.hostname }}-{{ execution.id[:8] }}"

  - id: work
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      # 1) Pull current file from Namespace Files (or initialize if missing)
      - id: fetch_from_namespace
        type: io.kestra.plugin.core.namespace.DownloadFiles
        namespace: "{{ flow.namespace }}"
        files:
          - "{{ vars.ns_inventory_path }}"
        allowFailure: true

      # 2) Upsert hostname (no ansible_host; DNS will resolve it)
      - id: upsert_yaml
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: "io.kestra.plugin.scripts.runner.docker.Docker"
          image: python:3.11-alpine
        commands:
          - |
            set -euo pipefail
            python -m pip install --no-cache-dir --upgrade pip ruamel.yaml
            python - <<'PY'
            import pathlib
            from ruamel.yaml import YAML
            from ruamel.yaml.comments import CommentedMap

            inv_path = pathlib.Path("{{ vars.ns_inventory_path }}")
            host = "{{ vars.host }}"

            yaml = YAML()
            yaml.indent(mapping=2, sequence=4, offset=2)

            data = CommentedMap()
            if inv_path.exists() and inv_path.stat().st_size > 0:
                with inv_path.open("r") as f:
                    data = yaml.load(f) or CommentedMap()

            data.setdefault("all", CommentedMap())
            data["all"].setdefault("hosts", CommentedMap())

            # Ensure host key exists with empty mapping
            if host not in data["all"]["hosts"] or data["all"]["hosts"][host] is None:
                data["all"]["hosts"][host] = CommentedMap()

            inv_path.parent.mkdir(parents=True, exist_ok=True)
            with inv_path.open("w") as f:
                yaml.dump(data, f)
            PY

      # 3) Validate with ansible-inventory
      - id: ansible_inventory_check
        type: io.kestra.plugin.ansible.cli.AnsibleCLI
        containerImage: cytopia/ansible:latest-tools
        namespaceFiles:
          enabled: true
          include:
            - "{{ vars.ns_inventory_path }}"
        outputFiles:
          - ansible-inventory.json
        commands:
          - ansible-inventory -i "{{ vars.ns_inventory_path }}" --list | tee ansible-inventory.json

      # 4) Write updated file back to Namespace Files
      - id: upload_to_namespace
        type: io.kestra.plugin.core.namespace.UploadFiles
        filesMap:
          "{{ vars.ns_inventory_path }}": "{{ vars.ns_inventory_path }}"

  # 5) Push just this file to a feature branch
  - id: push_namespace_files_to_git
    type: io.kestra.plugin.git.PushNamespaceFiles
    namespace: "{{ flow.namespace }}"
    files: "{{ vars.ns_inventory_path }}"
    gitDirectory: ""     # or "." if your Git host prefers it
    url: "{{ vars.git_url }}"
    branch: "{{ vars.feature_branch }}"
    username: "{{ secret('GIT_USERNAME') }}"
    password: "{{ secret('GIT_TOKEN') }}"
    authorName: "{{ vars.commit_author_name }}"
    authorEmail: "{{ vars.commit_author_email }}"
    commitMessage: "inventory: add {{ vars.host }}"
    delete: false

  # 6) Open a PR embedding ansible-inventory output
  - id: open_pr
    type: io.kestra.plugin.github.pulls.Create
    oauthToken: "{{ secret('GITHUB_TOKEN') }}"
    repository: "jcbolling/bollingnet-homelab"
    sourceBranch: "{{ vars.feature_branch }}"
    targetBranch: "{{ vars.target_branch }}"
    title: "Add {{ vars.host }} to inventory"
    body: |
      This PR was created by Kestra.

      **Host:** `{{ vars.host }}`

      ### `ansible-inventory --list` (JSON)
      ```json
      {{ read(outputs.ansible_inventory_check.outputFiles["ansible-inventory.json"]) }}
      ```

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"