---
galaxy_info:
  role_name: autokuma
  description: Deploy AutoKuma and manage static Uptime Kuma resources like monitors, groups, and notifications.
  author: ""
  license: ""
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies: []
