apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: postgresql
spec:
  instances: 3
  storage:
    storageClass: longhorn-single-replica
    size: 10Gi